version: "3"

services:
  fml:
    container_name: fml-webserver
    hostname: fml
    env_file:
      - ops/env.sh
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    restart: on-failure:5
    volumes:
      - .:/code
    ports:
      - "8000:8000"

  db:
    image: mysql:5.6
    container_name: fml-mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=fml2019
      - MYSQL_DATABASE=fml2019
    volumes:
      - fml-data-mysql:/var/lib/mysql

  redis:
    image: redis
    container_name: fml-redis
    volumes:
      - fml-data-redis:/data

  celery:
    container_name: fml-celery
    env_file:
      - ops/env.sh
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    command: celery -A fml worker --concurrency=20 --loglevel=info
    restart: on-failure:5
    volumes:
      - .:/code

  celery-beat:
    container_name: fml-celery-beat
    env_file:
      - ops/env.sh
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    command: celery -A fml beat --loglevel=info  --pidfile=/opt/celeryd.pid
    restart: on-failure:5
    volumes:
      - .:/code

volumes:
  fml-data-mysql:
  fml-data-redis:
