# Generated by Django 2.1.7 on 2019-02-17 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Marblelympics',
            fields=[
                ('year', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('team_count', models.IntegerField(default=0)),
                ('total_players', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='marblelympics',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ml_hosted', to='marblelympics.Team'),
        ),
        migrations.AddField(
            model_name='marblelympics',
            name='teams',
            field=models.ManyToManyField(related_name='marblelympics', to='marblelympics.Team'),
        ),
        migrations.AddField(
            model_name='fantasyplayer',
            name='marblelympics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players', to='marblelympics.Marblelympics'),
        ),
        migrations.AddField(
            model_name='fantasyplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marblelympics', to='players.Player'),
        ),
        migrations.AddIndex(
            model_name='fantasyplayer',
            index=models.Index(fields=['marblelympics', 'player'], name='participant_index'),
        ),
        migrations.AddIndex(
            model_name='fantasyplayer',
            index=models.Index(fields=['player'], name='player_index'),
        ),
        migrations.AlterUniqueTogether(
            name='fantasyplayer',
            unique_together={('player', 'marblelympics')},
        ),
    ]
