# Generated by Django 2.1.7 on 2019-02-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marblelympics', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['participation'], name='team_ml_index'),
        ),
    ]
