# Generated by Django 2.1.7 on 2019-02-17 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marblelympics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['ml', 'number'],
            },
        ),
        migrations.CreateModel(
            name='PlayerEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=-1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_entries', to='marblelympics.Event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_entries', to='marblelympics.FantasyPlayer')),
            ],
            options={
                'ordering': ['event', 'rank'],
            },
        ),
        migrations.AlterModelOptions(
            name='marblelympics',
            options={'ordering': ['year']},
        ),
        migrations.AddField(
            model_name='event',
            name='ml',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='marblelympics.Marblelympics'),
        ),
        migrations.AddIndex(
            model_name='playerentry',
            index=models.Index(fields=['event', 'player'], name='entry_index'),
        ),
        migrations.AddIndex(
            model_name='playerentry',
            index=models.Index(fields=['player'], name='player_entry_index'),
        ),
        migrations.AlterUniqueTogether(
            name='playerentry',
            unique_together={('player', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('ml', 'number')},
        ),
    ]
