# Generated by Django 2.1.7 on 2019-02-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marblelympics', '0002_auto_20190217_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='marblelympics',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
