# Generated by Django 2.1.7 on 2019-02-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marblelympics', '0002_auto_20190215_0709'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='team',
            name='team_ml_index',
        ),
        migrations.RemoveField(
            model_name='team',
            name='participation',
        ),
        migrations.AddField(
            model_name='marblelympics',
            name='team_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marblelympics',
            name='teams',
            field=models.ManyToManyField(related_name='marblelympics', to='marblelympics.Team'),
        ),
    ]
