# Generated by Django 2.1.7 on 2019-02-20 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marblelympics', '0003_marblelympics_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fantasyplayer',
            name='marblelympics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players_participating', to='marblelympics.Marblelympics'),
        ),
        migrations.AlterField(
            model_name='fantasyplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marblelympics_participated', to='players.Player'),
        ),
    ]
