# Generated by Django 2.1.7 on 2019-02-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marblelympics', '0004_auto_20190220_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marblelympics',
            name='teams',
            field=models.ManyToManyField(related_name='ml_participated', to='marblelympics.Team'),
        ),
    ]
