# Generated by Django 2.1.7 on 2019-02-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marblelympics', '0006_playerentry_selections'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
