# Generated by Django 2.1.7 on 2019-02-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marblelympics', '0007_event_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyplayer',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fantasyplayer',
            name='rank',
            field=models.IntegerField(default=-1),
        ),
    ]
