# Generated by Django 2.1.7 on 2019-03-12 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marblelympics', '0008_auto_20190226_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['ml', 'number'], 'verbose_name': 'Marblelympics Event', 'verbose_name_plural': 'Marblelympics Events'},
        ),
        migrations.AlterModelOptions(
            name='fantasyplayer',
            options={'verbose_name': 'Fantasy Player', 'verbose_name_plural': 'Fantasy Players'},
        ),
        migrations.AlterModelOptions(
            name='marblelympics',
            options={'ordering': ['year'], 'verbose_name': 'Marblelympics', 'verbose_name_plural': 'Marblelympics'},
        ),
        migrations.AlterModelOptions(
            name='playerentry',
            options={'ordering': ['event', 'rank'], 'verbose_name': 'Player Event Entry', 'verbose_name_plural': 'Player Event Entries'},
        ),
    ]
