# Generated by Django 2.1.7 on 2019-03-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marblelympics', '0010_remove_marblelympics_total_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='locked',
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.IntegerField(choices=[(1, 'OPEN'), (2, 'POINTS_UPDATING'), (3, 'RANK_UPDATING'), (4, 'LOCKED')], default=1),
        ),
    ]
