# Generated by Django 2.1.7 on 2019-03-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marblelympics', '0012_auto_20190320_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='scoring_status',
            field=models.IntegerField(choices=[(1, 'OPEN'), (2, 'ONGOING'), (3, 'COMPLETED')], default=1),
        ),
    ]
